---
# This playbook deploys a simple standalone Tomcat 7 ot 8 with JDK 8

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  pre_tasks:
    - debug: var=version
 # choice the tomcat version
  roles:  
    - { role: tomcat7, when: version == 7 }
    - { role: tomcat8, when: version == 8 }
